version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 992382443897.dkr.ecr.us-east-1.amazonaws.com
      - export REPOSITORY_URI=992382443897.dkr.ecr.us-east-1.amazonaws.com/ecs-demo
      - export IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t ecs-demo .
      - docker tag ecs-demo:latest 992382443897.dkr.ecr.us-east-1.amazonaws.com/ecs-demo:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image to Amazon ECR...
      - docker push 992382443897.dkr.ecr.us-east-1.amazonaws.com/ecs-demo:latest
      - echo Writing image definitions file...
      - printf '[{"name":"demo-ecs-codepipeline","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
